# FROM openjdk:17 AS build
# ENV LANGUAGE='en_US:en'
# ADD . /app
# WORKDIR /app

# # Copy the necessary files
# COPY src src
# COPY mvnw .
# COPY .mvn .mvn
# COPY mvnw.cmd .
# COPY pom.xml .

# # Build the application
# RUN chmod +x mvnw && \
#     bash -c './mvnw clean package -Dquarkus.package.type=fast-jar -DskipTests'

# FROM openjdk:17 AS runtime
# WORKDIR /app

# # Copy the built artifact from the build stage
# COPY --from=build /app/target/quarkus-app /app/target/quarkus-app

# #RUN mkdir -p /app/data/attachment

# #RUN chgrp -R 0 /app/data/attachment && chmod -R g=u /app/data/attachment

# RUN chgrp -R 0 /app && chmod -R g=u /app

# CMD ["java", "-jar", "/app/target/quarkus-app/quarkus-run.jar"]