apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: quarkus-listener
spec:
  serviceAccountName: tekton-sa
  triggers:
    - name: quarkus-trigger
      bindings:
        - ref: quarkus-triggerbinding
      template:
        ref: quarkus-triggertemplate
