apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: quarkus-triggertemplate
spec:
  params:
    - name: git-repo-url
    - name: git-revision
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: quarkus-pipeline-run
      spec:
        serviceAccountName: tekton-sa
        pipelineRef:
          name: quarkus-pipeline
        params:
          - name: repo-url
            value: $(params.git-repo-url)
          - name: revision
            value: $(params.git-revision)
