apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: be-okr-pipeline
  namespace: test-project
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: https://github.com/fsmutimeer/quarkus-app-deploy.git
        - name: revision
          value: feroz

    - name: build-image
      taskRef:
        name: buildah
      runAfter:
        - fetch-source
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/test-project/be-okr:latest

    - name: deploy-app
      taskRef:
        name: openshift-client
      runAfter:
        - build-image
      params:
        - name: SCRIPT
          value: |
            oc apply -f /workspace/shared-workspace/k8s/deployment.yaml -n test-project
