apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: quarkus-app-pipeline
  namespace: feroz-shah-dev
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: git-repo-url
      type: string
      default: "https://github.com/fsmutimeer/quarkus-app-deploy.git"
    - name: git-revision
      type: string
      default: "feroz"
    - name: image-name
      type: string
      default: "image-registry.openshift-image-registry.svc:5000/feroz-shah-dev/quarkus-app:latest"
  
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: "$(params.git-repo-url)"
        - name: revision
          value: "$(params.git-revision)"

    - name: build-image
      taskRef:
        name: buildah
      runAfter:
        - fetch-source
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: "$(params.image-name)"

    - name: deploy-app
      taskRef:
        name: openshift-client
      runAfter:
        - build-image
      params:
        - name: SCRIPT
          value: |
            cd $(workspaces.source.path)
            oc apply -f k8s/deployment.yaml -n feroz-shah-dev
            oc rollout status deployment/quarkus-app -n feroz-shah-dev --timeout=60s