apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
  namespace: feroz-shah-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-deploy
  namespace: feroz-shah-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: feroz-shah-dev