apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: quarkus-app-trigger
  namespace: feroz-shah-dev
spec:
  serviceAccountName: pipeline
  interceptors:
    - ref:
        name: "cel"
      params:
        - name: "overlays"
          value:
            - key: "X-Hub-Signature"
              expression: "1234567"
        - name: "filter"
          value: |
            header.match('X-Event-Key','repo:push') &&
            body.push.changes[0].new.name == 'feroz' &&
            body.repository.full_name == 'fsmutimeer/quarkus-app-deploy'
  bindings:
    - ref: quarkus-app-binding
  template:
    ref: quarkus-app-trigger-template