apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: quarkus-pipeline-template
  namespace: feroz-shah-dev
spec:
  params:
    - name: git-revision
      description: The git revision (branch/tag)
    - name: git-commit
      description: The git commit SHA
    - name: git-repo-url
      description: The git repository URL
  
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: quarkus-app-pipeline-run-
        namespace: feroz-shah-dev
      spec:
        pipelineRef:
          name: quarkus-app-pipeline
        params:
          - name: git-revision
            value: "refs/heads/feroz" # Hardcoded to your branch
          - name: git-repo-url
            value: "https://github.com/fsmutimeer/quarkus-app-deploy.git"
          - name: image-name
            value: "image-registry.openshift-image-registry.svc:5000/feroz-shah-dev/quarkus-app:latest"
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 1Gi