apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: quarkus-app-trigger-template
  namespace: feroz-shah-dev
spec:
  params:
    - name: username
      description: username for commit
    - name: useremail
      description: useremail for commit
    - name: git-repo-url
      description: The git repository url
    - name: git-revision
      description: The git revision
      default: feroz
    - name: deployment-name
      description: The name of the deployment to be created / patched
      default: ' '
    - name: dockerfile-path
      description: The path to the docker file
      default: none 
    - name: deployment-git-url
    - name : git-revision-deploy
    - name: git-commit-id
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: build-deploy-$(tt.params.deployment-name)-
        params:
          - name: username
            value: $(tt.params.username)
          - name: useremail
            value: $(tt.params.useremail)
          - name: deployment-name
            value: $(tt.params.deployment-name)
          - name: dockerfile-path
            value: $(tt.params.dockerfile-path)
          - name: git-url 
            value: $(tt.params.git-repo-url)
          - name: deployment-git-url
            value: $(tt.params.deployment-git-url)
          - name: git-revision-deploy
            value: $(tt.params.git-revision-deploy)
          - name: git-revision
            value: $(tt.params.git-revision)
          - name: image-url
            value: >-
              image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(tt.params.deployment-name)
        pipelineRef:
          name: build-and-deploy
        serviceAccountName: pipeline
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 500Mi
                storageClassName: lvms-vg1

          

