name: Build, Push & Deploy to OpenShift

on:
  push:
    branches:
      - feroz

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install OpenShift CLI (`oc`)
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xvf oc.tar.gz
          chmod +x oc
          sudo mv oc /usr/local/bin/
          oc version --client

      - name: Log in to OpenShift
        run: |
          oc login --token=${{ secrets.OPENSHIFT_TOKEN }} --server=https://api.cl0101.cloud22.io
          echo "Logged into OpenShift"

      - name: Get OpenShift Registry URL
        run: |
          IMAGE_REGISTRY=$(oc get route image-registry -n openshift-image-registry --template='{{ .spec.host }}' 2>/dev/null || echo "image-registry.openshift-image-registry.svc:5000")
          echo "IMAGE_REGISTRY=$IMAGE_REGISTRY" >> $GITHUB_ENV
          echo "Using OpenShift Image Registry: $IMAGE_REGISTRY"

      - name: Log in to OpenShift Registry
        run: |
          echo "${{ secrets.OPENSHIFT_PASSWORD }}" | docker login -u "${{ secrets.OPENSHIFT_USERNAME }}" --password-stdin $IMAGE_REGISTRY

      - name: Build and Tag Docker Image
        run: |
          docker build -t $IMAGE_REGISTRY/test-project/quarkus-app:latest .
          echo "Docker image built successfully"

      - name: Push Image to OpenShift
        run: |
          docker push $IMAGE_REGISTRY/test-project/quarkus-app:latest
          echo "Docker image pushed successfully"

      - name: Restart OpenShift Deployment
        run: |
          oc rollout restart deployment/quarkus-app -n test-project
          echo "Deployment restarted successfully"
