## A basic GitHub Actions workflow for your Quarkus application.

name: CI build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "building and testing the app ..."
  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - 
        name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ferozshahit22/quarkus-app:${{ github.sha }}

  update-image-tag-in-helm:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - run: |
          git config --global user.email ci-bot@argocd.com &&  git config --global user.name ci-bot
          echo "Cloning app repo..."
          git clone https://oauth2:${{ secrets.GH_PAT }}@github.com/fsmutimeer/argo-cd.git
          cd quarkus-app-deploy
          echo "Updating image tag in values file..."
          # Using proper sed syntax with escaped slashes
          sed -i "s|tag: .*|tag: ${{ github.sha }}|g" helm/quarkusapp/values.yaml
          git add . && git commit -m "Update image tag to ${{ github.sha }} [skip ci]"
          git push
  add_labels:
    runs-on : ubuntu-latest
    needs: update-image-tag-in-helm
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            preview

