name: CI Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and test
        run: |
          echo "Building and testing the app..."
          ./mvnw clean test

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ferozshahit22/quarkus-app:${{ github.sha }}
            ferozshahit22/quarkus-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-image-tag-in-helm:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Checkout Helm repo
        uses: actions/checkout@v3
        with:
          repository: fsmutimeer/quarkus-app-deploy
          token: ${{ secrets.GH_PAT || github.token }}
          path: helm-repo
      - name: Update image tag
        working-directory: ./helm-repo
        run: |
          git config user.email "ci-bot@argocd.com"
          git config user.name "ci-bot"
          # Using yq for more reliable YAML editing (install first)
          sudo snap install yq
          yq e ".image.tag = \"${{ github.sha }}\"" -i helm/quarkuapp/values.yaml
          git add helm/quarkuapp/values.yaml
          git commit -m "Update image tag to ${{ github.sha }} [skip ci]"
          git push

  add_labels:
    runs-on: ubuntu-latest
    needs: update-image-tag-in-helm
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: preview
          github_token: ${{ github.token }}