name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and test
        run: |
          echo "Building and testing the application..."
          ./mvnw clean test

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ferozshahit22/quarkus-app:${{ github.sha }}
            ferozshahit22/quarkus-app:latest

  helm-update:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Checkout Helm repo
        uses: actions/checkout@v3
        with:
          repository: fsmutimeer/quarkus-app-deploy
          token: ${{ secrets.GH_PAT }}
          path: helm-repo
          fetch-depth: 0

      - name: Configure Git
        working-directory: ./helm-repo
        run: |
          git config user.email "ci-bot@argocd.com"
          git config user.name "ci-bot"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GH_PAT }}@github.com/fsmutimeer/quarkus-app-deploy.git

      - name: Update Helm values
        working-directory: ./helm-repo
        run: |
          # Update image tag using yq
          yq eval '.image.tag = "${{ github.sha }}"' -i helm/quarkuapp/values.yaml
          
          # Verify changes
          echo "Updated values.yaml content:"
          cat helm/quarkuapp/values.yaml
          
          # Commit and push
          git add helm/quarkuapp/values.yaml
          git commit -m "CI: Update image tag to ${{ github.sha }} [skip ci]"
          git pull --rebase origin main
          git push origin HEAD:main

  add-labels:
    runs-on: ubuntu-latest
    needs: helm-update
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: "preview"
          github_token: ${{ github.token }}